article:
video:
images:
  - title:
    url:
assembly:
  - name: HARDWARIO Button Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Mini Battery Module
  - name: HARDWARIO Encoder Module
  - name: HARDWARIO Lux Meter Tag
  - name: HARDWARIO PIR Module
  - name: HARDWARIO Power Module

